// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#include "../ui.h"

void ui_comp_Button1_create_hook( lv_obj_t * comp)
{
}
