// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_IntroScreen_screen_init(void)
{
    ui_IntroScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_IntroScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReadMeasurements = lv_btn_create(ui_IntroScreen);
    lv_obj_set_width(ui_ReadMeasurements, 100);
    lv_obj_set_height(ui_ReadMeasurements, 50);
    lv_obj_set_x(ui_ReadMeasurements, 100);
    lv_obj_set_y(ui_ReadMeasurements, -87);
    lv_obj_set_align(ui_ReadMeasurements, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReadMeasurements, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ReadMeasurements, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Challenge = lv_btn_create(ui_IntroScreen);
    lv_obj_set_width(ui_Challenge, 208);
    lv_obj_set_height(ui_Challenge, 50);
    lv_obj_set_x(ui_Challenge, -7);
    lv_obj_set_y(ui_Challenge, 67);
    lv_obj_set_align(ui_Challenge, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Challenge, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Challenge, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Challenge, lv_color_hex(0x0EE760), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Challenge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiSettings = lv_btn_create(ui_IntroScreen);
    lv_obj_set_width(ui_WifiSettings, 100);
    lv_obj_set_height(ui_WifiSettings, 50);
    lv_obj_set_x(ui_WifiSettings, -102);
    lv_obj_set_y(ui_WifiSettings, -88);
    lv_obj_set_align(ui_WifiSettings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WifiSettings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_WifiSettings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ReadMeasurements, ui_event_ReadMeasurements, LV_EVENT_ALL, NULL);

}
