// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#include "../ui.h"

void ui_mapScreen_screen_init(void)
{
ui_mapScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_mapScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mapPanel = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_mapPanel, 200);
lv_obj_set_height( ui_mapPanel, 200);
lv_obj_set_x( ui_mapPanel, -40 );
lv_obj_set_y( ui_mapPanel, 0 );
lv_obj_set_align( ui_mapPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_mapPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_mapPanel, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_mapPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_mapPanel, lv_color_hex(0x040355), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_mapPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_mapPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_mapPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_mapPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_mapScreenInfoSubmarine = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenInfoSubmarine, 68);
lv_obj_set_height( ui_mapScreenInfoSubmarine, 19);
lv_obj_set_x( ui_mapScreenInfoSubmarine, 110 );
lv_obj_set_y( ui_mapScreenInfoSubmarine, -63 );
lv_obj_set_align( ui_mapScreenInfoSubmarine, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mapScreenInfoSubmarine,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mapScreenInfoSubmarine, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_mapScreenInfoSubmarine, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mapLabelSubmarineNum = lv_label_create(ui_mapScreenInfoSubmarine);
lv_obj_set_width( ui_mapLabelSubmarineNum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapLabelSubmarineNum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mapLabelSubmarineNum, 106 );
lv_obj_set_y( ui_mapLabelSubmarineNum, -61 );
lv_obj_set_align( ui_mapLabelSubmarineNum, LV_ALIGN_CENTER );

ui_mapScreenInfoKraken = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenInfoKraken, 68);
lv_obj_set_height( ui_mapScreenInfoKraken, 19);
lv_obj_set_x( ui_mapScreenInfoKraken, 110 );
lv_obj_set_y( ui_mapScreenInfoKraken, 35 );
lv_obj_set_align( ui_mapScreenInfoKraken, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mapScreenInfoKraken,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mapScreenInfoKraken, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_mapScreenInfoKraken, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mapLabelKrakenNum = lv_label_create(ui_mapScreenInfoKraken);
lv_obj_set_width( ui_mapLabelKrakenNum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapLabelKrakenNum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mapLabelKrakenNum, LV_ALIGN_CENTER );

ui_mapScreenInfoDistance = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenInfoDistance, 68);
lv_obj_set_height( ui_mapScreenInfoDistance, 19);
lv_obj_set_x( ui_mapScreenInfoDistance, 110 );
lv_obj_set_y( ui_mapScreenInfoDistance, -14 );
lv_obj_set_align( ui_mapScreenInfoDistance, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_mapScreenInfoDistance,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_mapScreenInfoDistance, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_mapScreenInfoDistance, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mapLabelDistanceNum = lv_label_create(ui_mapScreenInfoDistance);
lv_obj_set_width( ui_mapLabelDistanceNum, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapLabelDistanceNum, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_mapLabelDistanceNum, LV_ALIGN_CENTER );

ui_mapScreenLabelSub = lv_label_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenLabelSub, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapScreenLabelSub, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mapScreenLabelSub, 111 );
lv_obj_set_y( ui_mapScreenLabelSub, -81 );
lv_obj_set_align( ui_mapScreenLabelSub, LV_ALIGN_CENTER );
lv_label_set_text(ui_mapScreenLabelSub,"SUBMARINE");

ui_mapScreenLabelDist = lv_label_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenLabelDist, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapScreenLabelDist, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mapScreenLabelDist, 111 );
lv_obj_set_y( ui_mapScreenLabelDist, -32 );
lv_obj_set_align( ui_mapScreenLabelDist, LV_ALIGN_CENTER );
lv_label_set_text(ui_mapScreenLabelDist,"DISTANCE");

ui_mapScreenLabelKraken = lv_label_create(ui_mapScreen);
lv_obj_set_width( ui_mapScreenLabelKraken, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mapScreenLabelKraken, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mapScreenLabelKraken, 111 );
lv_obj_set_y( ui_mapScreenLabelKraken, 13 );
lv_obj_set_align( ui_mapScreenLabelKraken, LV_ALIGN_CENTER );
lv_label_set_text(ui_mapScreenLabelKraken,"KRAKEN");

ui_playerPanel = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_playerPanel, 35);
lv_obj_set_height( ui_playerPanel, 35);
lv_obj_set_x( ui_playerPanel, -123 );
lv_obj_set_y( ui_playerPanel, 82 );
lv_obj_set_align( ui_playerPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_playerPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_playerPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_playerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_playerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_playerPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_playerPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_krakenPanel = lv_obj_create(ui_mapScreen);
lv_obj_set_width( ui_krakenPanel, 35);
lv_obj_set_height( ui_krakenPanel, 35);
lv_obj_set_x( ui_krakenPanel, 42 );
lv_obj_set_y( ui_krakenPanel, -83 );
lv_obj_set_align( ui_krakenPanel, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_krakenPanel, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_krakenPanel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_krakenPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_krakenPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_krakenPanel, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_krakenPanel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);


}
