// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#include "../ui.h"

void ui_ProvisionScreen_screen_init(void)
{
ui_ProvisionScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ProvisionScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_ProvisionScreen);
lv_obj_set_width( ui_Button2, 30);
lv_obj_set_height( ui_Button2, 29);
lv_obj_set_x( ui_Button2, -36 );
lv_obj_set_y( ui_Button2, 51 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 89 );
lv_obj_set_y( ui_Label4, -98 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"KRAKEN HUNT");
lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ConnectButton = lv_btn_create(ui_ProvisionScreen);
lv_obj_set_width( ui_ConnectButton, 31);
lv_obj_set_height( ui_ConnectButton, 31);
lv_obj_set_x( ui_ConnectButton, 35 );
lv_obj_set_y( ui_ConnectButton, 51 );
lv_obj_set_align( ui_ConnectButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UpperButton = lv_btn_create(ui_ProvisionScreen);
lv_obj_set_width( ui_UpperButton, 33);
lv_obj_set_height( ui_UpperButton, 29);
lv_obj_set_x( ui_UpperButton, -1 );
lv_obj_set_y( ui_UpperButton, 18 );
lv_obj_set_align( ui_UpperButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_UpperButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_UpperButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_UpperButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_UpperButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LowerButton = lv_btn_create(ui_ProvisionScreen);
lv_obj_set_width( ui_LowerButton, 35);
lv_obj_set_height( ui_LowerButton, 32);
lv_obj_set_x( ui_LowerButton, -1 );
lv_obj_set_y( ui_LowerButton, 88 );
lv_obj_set_align( ui_LowerButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_LowerButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_LowerButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LowerButton, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LowerButton, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -102 );
lv_obj_set_y( ui_Label2, 52 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"CHANGE\nNETWORK");

ui_Label3 = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 98 );
lv_obj_set_y( ui_Label3, 52 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"CONNECT");

ui_wifiStatus = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_wifiStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_wifiStatus, -87 );
lv_obj_set_y( ui_wifiStatus, -98 );
lv_obj_set_align( ui_wifiStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_wifiStatus,"WIFI NOT AVAILABLE");
lv_obj_set_style_text_font(ui_wifiStatus, &lv_font_montserrat_12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SsidLabel = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_SsidLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SsidLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SsidLabel, -135 );
lv_obj_set_y( ui_SsidLabel, -71 );
lv_obj_set_align( ui_SsidLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SsidLabel,"SSID:");

ui_startGameLabel = lv_label_create(ui_ProvisionScreen);
lv_obj_set_width( ui_startGameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_startGameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_startGameLabel, 49 );
lv_obj_set_y( ui_startGameLabel, 89 );
lv_obj_set_align( ui_startGameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_startGameLabel,"START");

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_UpperButton, ui_event_UpperButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_LowerButton, ui_event_LowerButton, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ProvisionScreen, ui_event_ProvisionScreen, LV_EVENT_ALL, NULL);

}
