// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_IntroScreen
void ui_IntroScreen_screen_init(void);
lv_obj_t *ui_IntroScreen;
lv_obj_t *ui_Image1;
void ui_event_Challenge( lv_event_t * e);
lv_obj_t *ui_Challenge;
lv_obj_t *ui_Fight_an_Alien;
void ui_event_WifiSettings( lv_event_t * e);
lv_obj_t *ui_WifiSettings;
lv_obj_t *ui_Wifi_Settings;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Station_Sensors;


// SCREEN: ui_WifiScreen
void ui_WifiScreen_screen_init(void);
void ui_event_WifiScreen( lv_event_t * e);
lv_obj_t *ui_WifiScreen;
void ui_event_Button8( lv_event_t * e);
lv_obj_t *ui_Button8;
lv_obj_t *ui_ProvisionLabel;
void ui_event_WifiConnectButton( lv_event_t * e);
lv_obj_t *ui_WifiConnectButton;
lv_obj_t *ui_ConnectToWifiLabel;
void ui_event_BackHome( lv_event_t * e);
lv_obj_t *ui_BackHome;
lv_obj_t *ui_BackFromWifi;
lv_obj_t *ui_WIfiAvailability;
lv_obj_t *ui_WifiAvailability;


// SCREEN: ui_AlienTicTacToe
void ui_AlienTicTacToe_screen_init(void);
lv_obj_t *ui_AlienTicTacToe;
void ui_event_Button13( lv_event_t * e);
lv_obj_t *ui_Button13;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Panel4;
void ui_event_poz0( lv_event_t * e);
lv_obj_t *ui_poz0;
lv_obj_t *ui_znak0;
void ui_event_poz1( lv_event_t * e);
lv_obj_t *ui_poz1;
lv_obj_t *ui_znak1;
void ui_event_poz2( lv_event_t * e);
lv_obj_t *ui_poz2;
lv_obj_t *ui_znak2;
void ui_event_poz3( lv_event_t * e);
lv_obj_t *ui_poz3;
lv_obj_t *ui_znak3;
void ui_event_poz4( lv_event_t * e);
lv_obj_t *ui_poz4;
lv_obj_t *ui_znak4;
void ui_event_poz5( lv_event_t * e);
lv_obj_t *ui_poz5;
lv_obj_t *ui_znak5;
void ui_event_poz6( lv_event_t * e);
lv_obj_t *ui_poz6;
lv_obj_t *ui_znak6;
void ui_event_poz7( lv_event_t * e);
lv_obj_t *ui_poz7;
lv_obj_t *ui_znak7;
void ui_event_poz8( lv_event_t * e);
lv_obj_t *ui_poz8;
lv_obj_t *ui_znak8;
lv_obj_t *ui_Label6;


// SCREEN: ui_MeasurementsScreen
void ui_MeasurementsScreen_screen_init(void);
lv_obj_t *ui_MeasurementsScreen;
void ui_event_BackFromSensor( lv_event_t * e);
lv_obj_t *ui_BackFromSensor;
lv_obj_t *ui_backFromSensorLab;
lv_obj_t *ui_tempPanel;
lv_obj_t *ui_tempLabel;
lv_obj_t *ui_humidPanel;
lv_obj_t *ui_humidLabel;
lv_obj_t *ui_accPanel;
lv_obj_t *ui_accLabel;
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Challenge( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_AlienTicTacToe, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_AlienTicTacToe_screen_init);
      challenge( e );
}
}
void ui_event_WifiSettings( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_WifiScreen, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WifiScreen_screen_init);
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MeasurementsScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_MeasurementsScreen_screen_init);
}
}
void ui_event_WifiScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_events_is_wifi_available( e );
}
}
void ui_event_Button8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      start_provision( e );
}
}
void ui_event_WifiConnectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      connect_to_wifi( e );
}
}
void ui_event_BackHome( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_IntroScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_IntroScreen_screen_init);
}
}
void ui_event_Button13( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_IntroScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_IntroScreen_screen_init);
      exit_game( e );
}
}
void ui_event_poz0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz0callback( e );
}
}
void ui_event_poz1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz1callback( e );
}
}
void ui_event_poz2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz2callback( e );
}
}
void ui_event_poz3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz3callback( e );
}
}
void ui_event_poz4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz4callback( e );
}
}
void ui_event_poz5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz5callback( e );
}
}
void ui_event_poz6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz6callback( e );
}
}
void ui_event_poz7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz7callback( e );
}
}
void ui_event_poz8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      poz8callback( e );
}
}
void ui_event_BackFromSensor( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_IntroScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_IntroScreen_screen_init);
}
}
void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_setup( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_IntroScreen_screen_init();
ui_WifiScreen_screen_init();
ui_AlienTicTacToe_screen_init();
ui_MeasurementsScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_IntroScreen);
}
