// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ProvisionScreen
void ui_ProvisionScreen_screen_init(void);
void ui_event_ProvisionScreen( lv_event_t * e);
lv_obj_t *ui_ProvisionScreen;
void ui_event_Button2( lv_event_t * e);
lv_obj_t *ui_Button2;
lv_obj_t *ui_Label4;
void ui_event_ConnectButton( lv_event_t * e);
lv_obj_t *ui_ConnectButton;
void ui_event_UpperButton( lv_event_t * e);
lv_obj_t *ui_UpperButton;
void ui_event_LowerButton( lv_event_t * e);
lv_obj_t *ui_LowerButton;
lv_obj_t *ui_Label2;
lv_obj_t *ui_Label3;
lv_obj_t *ui_wifiStatus;
lv_obj_t *ui_SsidLabel;
lv_obj_t *ui_startGameLabel;


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_Panel1;
lv_obj_t *ui_Label5;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Panel3;
lv_obj_t *ui_Label7;
lv_obj_t *ui_mainScreenDiverLabel;
lv_obj_t *ui_Label12;
lv_obj_t *ui_Panel7;
lv_obj_t *ui_mainScreenInfo;
lv_obj_t *ui_Label8;
lv_obj_t *ui_Panel4;
lv_obj_t *ui_SubmarinePosition;
lv_obj_t *ui_Label9;
lv_obj_t *ui_Panel2;
lv_obj_t *ui_DistanceFromKraken;
lv_obj_t *ui_Label10;
lv_obj_t *ui_Panel5;
lv_obj_t *ui_KrakenPosition;
lv_obj_t *ui_MainScreenWeaponPanel;
void ui_event_Button4( lv_event_t * e);
lv_obj_t *ui_Button4;
lv_obj_t *ui_torpedoLabel;
lv_obj_t *ui_Button6;
lv_obj_t *ui_netLabel;
lv_obj_t *ui_Button1;
lv_obj_t *ui_lightLabel;
void ui_event_exitButton( lv_event_t * e);
lv_obj_t *ui_exitButton;


// SCREEN: ui_mapScreen
void ui_mapScreen_screen_init(void);
lv_obj_t *ui_mapScreen;
lv_obj_t *ui_mapPanel;
lv_obj_t *ui_mapScreenInfoSubmarine;
lv_obj_t *ui_mapLabelSubmarineNum;
lv_obj_t *ui_mapScreenInfoKraken;
lv_obj_t *ui_mapLabelKrakenNum;
lv_obj_t *ui_mapScreenInfoDistance;
lv_obj_t *ui_mapLabelDistanceNum;
lv_obj_t *ui_mapScreenLabelSub;
lv_obj_t *ui_mapScreenLabelDist;
lv_obj_t *ui_mapScreenLabelKraken;
lv_obj_t *ui_playerPanel;
lv_obj_t *ui_krakenPanel;


// SCREEN: ui_endGameScreen
void ui_endGameScreen_screen_init(void);
lv_obj_t *ui_endGameScreen;
lv_obj_t *ui_gameResultPanel;
lv_obj_t *ui_gameResultLabel;
void ui_event____initial_actions0( lv_event_t * e);
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_ProvisionScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_events_is_wifi_available( e );
}
}
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      start_provision( e );
}
}
void ui_event_ConnectButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      connect_to_wifi( e );
}
}
void ui_event_UpperButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_MainScreen_screen_init);
}
}
void ui_event_LowerButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_NONE, 10, 0, &ui_MainScreen_screen_init);
}
if ( event_code == LV_EVENT_CLICKED) {
      ui_game_start_up( e );
}
}
void ui_event_MainScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      ui_make_weapons_group( e );
}
}
void ui_event_Button4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProvisionScreen, LV_SCR_LOAD_ANIM_NONE, 10, 0, &ui_ProvisionScreen_screen_init);
}
}
void ui_event_exitButton( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      exit_game( e );
}
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_ProvisionScreen, LV_SCR_LOAD_ANIM_NONE, 10, 0, &ui_ProvisionScreen_screen_init);
}
}
void ui_event____initial_actions0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_event_startup_wifi( e );
}
if ( event_code == LV_EVENT_SCREEN_LOAD_START) {
      ui_setup( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), true, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_ProvisionScreen_screen_init();
ui_MainScreen_screen_init();
ui_mapScreen_screen_init();
ui_endGameScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_obj_add_event_cb(ui____initial_actions0, ui_event____initial_actions0, LV_EVENT_ALL, NULL);

lv_disp_load_scr(ui____initial_actions0);
lv_disp_load_scr( ui_ProvisionScreen);
}
