// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#ifndef _KRAKEN_HUNT_UI_H
#define _KRAKEN_HUNT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "components/ui_comp.h"
#include "components/ui_comp_hook.h"
#include "ui_events.h"
// SCREEN: ui_ProvisionScreen
void ui_ProvisionScreen_screen_init(void);
void ui_event_ProvisionScreen( lv_event_t * e);
extern lv_obj_t *ui_ProvisionScreen;
void ui_event_Button2( lv_event_t * e);
extern lv_obj_t *ui_Button2;
extern lv_obj_t *ui_Label4;
void ui_event_ConnectButton( lv_event_t * e);
extern lv_obj_t *ui_ConnectButton;
void ui_event_UpperButton( lv_event_t * e);
extern lv_obj_t *ui_UpperButton;
void ui_event_LowerButton( lv_event_t * e);
extern lv_obj_t *ui_LowerButton;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_wifiStatus;
extern lv_obj_t *ui_SsidLabel;
extern lv_obj_t *ui_startGameLabel;
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen( lv_event_t * e);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_mainScreenDiverLabel;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_mainScreenInfo;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_SubmarinePosition;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_DistanceFromKraken;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_KrakenPosition;
extern lv_obj_t *ui_MainScreenWeaponPanel;
void ui_event_Button4( lv_event_t * e);
extern lv_obj_t *ui_Button4;
extern lv_obj_t *ui_torpedoLabel;
extern lv_obj_t *ui_Button6;
extern lv_obj_t *ui_netLabel;
extern lv_obj_t *ui_Button1;
extern lv_obj_t *ui_lightLabel;
void ui_event_exitButton( lv_event_t * e);
extern lv_obj_t *ui_exitButton;
// SCREEN: ui_mapScreen
void ui_mapScreen_screen_init(void);
extern lv_obj_t *ui_mapScreen;
extern lv_obj_t *ui_mapPanel;
extern lv_obj_t *ui_mapScreenInfoSubmarine;
extern lv_obj_t *ui_mapLabelSubmarineNum;
extern lv_obj_t *ui_mapScreenInfoKraken;
extern lv_obj_t *ui_mapLabelKrakenNum;
extern lv_obj_t *ui_mapScreenInfoDistance;
extern lv_obj_t *ui_mapLabelDistanceNum;
extern lv_obj_t *ui_mapScreenLabelSub;
extern lv_obj_t *ui_mapScreenLabelDist;
extern lv_obj_t *ui_mapScreenLabelKraken;
extern lv_obj_t *ui_playerPanel;
extern lv_obj_t *ui_krakenPanel;
// SCREEN: ui_endGameScreen
void ui_endGameScreen_screen_init(void);
extern lv_obj_t *ui_endGameScreen;
extern lv_obj_t *ui_gameResultPanel;
extern lv_obj_t *ui_gameResultLabel;
void ui_event____initial_actions0( lv_event_t * e);
extern lv_obj_t *ui____initial_actions0;




void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
