// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.4
// Project name: kraken_hunt

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_event_startup_wifi(lv_event_t * e);
void ui_setup(lv_event_t * e);
void ui_events_is_wifi_available(lv_event_t * e);
void start_provision(lv_event_t * e);
void connect_to_wifi(lv_event_t * e);
void ui_game_start_up(lv_event_t * e);
void ui_make_weapons_group(lv_event_t * e);
void exit_game(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
