// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_setup(lv_event_t * e);
void btn1_clicked(lv_event_t * e);
void start_provision(lv_event_t * e);
void connect_to_wifi(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
