// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_setup(lv_event_t * e)
{
	// Your code here
}

void btn1_clicked(lv_event_t * e)
{
	// Your code here
}

void ui_events_is_wifi_available(lv_event_t * e)
{
	// Your code here
}

void start_provision(lv_event_t * e)
{
	// Your code here
}

void connect_to_wifi(lv_event_t * e)
{
	// Your code here
}
